--- 
database_name: tobby
schema:
  - name: ratings
    tables:
      - name: category
        columns:
          - name: id
            type: INT
            primary_key: true
          - name: guild_id
            type: VARCHAR(32)
          - name: name
            type: varchar(255)
            nullable: false
          - name: description
            type: varchar(4000)
            nullable: true
          - name: created_at
            type: DATETIME2
            nullable: false
            default: GETDATE()
          - name: announcement_channel_id
            type: VARCHAR(32)
            nullable: true
      - name: metric
        columns:
          - name: id
            type: INT
            primary_key: true
          - name: category_id
            type: INT
          - name: name
            type: varchar(255)
            nullable: false
          - name: description
            type: varchar(4000)
            nullable: true
          - name: created_at
            type: DATETIME2
            nullable: false
            default: GETDATE()
      - name: item
        columns:
          - name: id
            type: INT
            primary_key: true
          - name: category_id
            type: INT
          - name: name
            type: varchar(255)
            nullable: false
          - name: description
            type: varchar(4000)
            nullable: true
          - name: available_to_rate_date
            type: DATETIME2
            nullable: false
            default: GETDATE()
          - name: created_at
            type: DATETIME2
            nullable: false
            default: GETDATE()
          - name: announced
            type: BIT
            nullable: false
            default: '0'
      - name: rating
        columns:
          - name: id
            type: INT
            primary_key: true
          - name: metric_id
            type: INT
          - name: item_id
            type: INT
          - name: rating
            type: INT
          - name: user_id
            type: VARCHAR(32)
          - name: created_at
            type: DATETIME2
            nullable: false
            default: GETDATE()

